<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Abhijith" failures="0" tests="9" name="testNG.ToExploreAnnotation" time="36.878" errors="1" timestamp="2023-02-20T17:02:37 IST" skipped="1">
  <testcase classname="testNG.ToExploreAnnotation" name="makeMyTrip" time="4.243"/>
  <system-out/>
  <testcase classname="testNG.ToExploreAnnotation" name="makeMyTrip" time="5.194"/>
  <system-out/>
  <testcase classname="testNG.ToExploreAnnotation" name="makeMyTrip" time="7.603"/>
  <system-out/>
  <testcase classname="testNG.ToExploreAnnotation" name="makeMyTrip" time="3.832"/>
  <system-out/>
  <testcase classname="testNG.ToExploreAnnotation" name="launchDemoWebShop" time="2.016">
    <error message="Method testNG.ToExploreAnnotation.launchDemoWebShop() didn&#039;t finish within the time-out 2000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testNG.ToExploreAnnotation.launchDemoWebShop() didn't finish within the time-out 2000
at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:371)
at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:282)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:605)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- launchDemoWebShop -->
  <system-out/>
  <testcase classname="testNG.ToExploreAnnotation" name="flipKart" time="4.629"/>
  <system-out/>
  <testcase classname="testNG.ToExploreAnnotation" name="flipKart" time="4.007"/>
  <system-out/>
  <testcase classname="testNG.ToExploreAnnotation" name="flipKart" time="5.354"/>
  <system-out/>
  <testcase classname="testNG.ToExploreAnnotation" name="launchWoodenStreet">
    <skipped/>
  </testcase> <!-- launchWoodenStreet -->
  <system-out/>
</testsuite> <!-- testNG.ToExploreAnnotation -->
